In [15]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [16]:
df=pd.read_csv("PhishingEmailData.csv", encoding="Latin-1")
df

,Email_Subject,Email_Content,Sending_Date,Sending_Time,Day,URL_Title,Coined.Word,Sender_Name,Sender_Title,Closing_Remarks,Sender_Email,Logo,To
0,URGENT REQUEST,Are you available ?\nNo calls text only 951307...,1/9/20,na,na,na,Urgent,Y,Chancellor\nBerkeley University of California,BEST REGARDS,cchristberkeley.edu@gmail.com,na,NB
1,Quick question,I'm in a meeting and need help getting some Am...,1/9/20,na,na,na,Quick,Y,"University of California, Berkeley",na,XXX.subdomain.berkeley.edu,na,NB
2,******Part time home work assistant needed******,Hello RECIPIENT\n\nI am urgently seeking for a...,10/19/19,2:22 PM,Sat,na,Job/Needed,Y,*Professor David Card*\n*Department of Economi...,Sincerely,dvdmson @ gmail . Com,na,NB
3,Ê vendor payment,Are you around? I need to pay a vendor with th...,12/27/18\n,na,na,na,"gift card, meeting",Y,"University of California, Berkeley",na,ÊÊXXX.subdomain.berkeley.edu@gmail.com,na,NB
4,Quick question,I'm in a meeting and need help getting some Am...,12/27/18\n,na,na,na,shared,Y,"University of California, Berkeley",na,XXX.subdomain.berkeley.edu,na,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Sales Contract PO:#224906999,2 new message,"February 12th, 2019",9.32am,tue,review,"sales, review",Y,Y,thanks,Y,na,B
185,new bill from Ian,your bill is here,"February 12th, 2019",2.15pm,tue,invoice connect,"bill,",Y,Y,thank you,Y,na,B
186,Re: Payment Invoice,please check your,"February 12th, 2019",2.17am EST,na,na,"invoice, payment",Y,Y,Thank you,Y,na,B
187,KSU Infringement,"email has been reposted , regulation","February 9th, 2019",11.21am EST,na,URL Redacted,"reported, regulations, policies",Y,Y,Sincerely,Y,na,B
188,We recieved your request,request to deactivate,"January 29th, 2019",2.11pm,tue,cancel,"request, cancel, deactivate,",Y,Y,na,Y,offcie 365,B

In [17]:
df.dropna(inplace=True)
df

,Email_Subject,Email_Content,Sending_Date,Sending_Time,Day,URL_Title,Coined.Word,Sender_Name,Sender_Title,Closing_Remarks,Sender_Email,Logo,To
0,URGENT REQUEST,Are you available ?\nNo calls text only 951307...,1/9/20,na,na,na,Urgent,Y,Chancellor\nBerkeley University of California,BEST REGARDS,cchristberkeley.edu@gmail.com,na,NB
1,Quick question,I'm in a meeting and need help getting some Am...,1/9/20,na,na,na,Quick,Y,"University of California, Berkeley",na,XXX.subdomain.berkeley.edu,na,NB
2,******Part time home work assistant needed******,Hello RECIPIENT\n\nI am urgently seeking for a...,10/19/19,2:22 PM,Sat,na,Job/Needed,Y,*Professor David Card*\n*Department of Economi...,Sincerely,dvdmson @ gmail . Com,na,NB
3,Ê vendor payment,Are you around? I need to pay a vendor with th...,12/27/18\n,na,na,na,"gift card, meeting",Y,"University of California, Berkeley",na,ÊÊXXX.subdomain.berkeley.edu@gmail.com,na,NB
6,Message from human resources,Dear XXXXX@berkeley.edu(link sends e-mail)\n\n...,4/13/17,9:29:54 PM PDT,na,click here,HR,Y,Berkeley University Of California HR Departmen...,Thank you,HR@berkeley.edu,na,NB
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Sales Contract PO:#224906999,2 new message,"February 12th, 2019",9.32am,tue,review,"sales, review",Y,Y,thanks,Y,na,B
185,new bill from Ian,your bill is here,"February 12th, 2019",2.15pm,tue,invoice connect,"bill,",Y,Y,thank you,Y,na,B
186,Re: Payment Invoice,please check your,"February 12th, 2019",2.17am EST,na,na,"invoice, payment",Y,Y,Thank you,Y,na,B
187,KSU Infringement,"email has been reposted , regulation","February 9th, 2019",11.21am EST,na,URL Redacted,"reported, regulations, policies",Y,Y,Sincerely,Y,na,B
188,We recieved your request,request to deactivate,"January 29th, 2019",2.11pm,tue,cancel,"request, cancel, deactivate,",Y,Y,na,Y,offcie 365,B

In [18]:
df.fillna("", inplace=True)
df

,Email_Subject,Email_Content,Sending_Date,Sending_Time,Day,URL_Title,Coined.Word,Sender_Name,Sender_Title,Closing_Remarks,Sender_Email,Logo,To
0,URGENT REQUEST,Are you available ?\nNo calls text only 951307...,1/9/20,na,na,na,Urgent,Y,Chancellor\nBerkeley University of California,BEST REGARDS,cchristberkeley.edu@gmail.com,na,NB
1,Quick question,I'm in a meeting and need help getting some Am...,1/9/20,na,na,na,Quick,Y,"University of California, Berkeley",na,XXX.subdomain.berkeley.edu,na,NB
2,******Part time home work assistant needed******,Hello RECIPIENT\n\nI am urgently seeking for a...,10/19/19,2:22 PM,Sat,na,Job/Needed,Y,*Professor David Card*\n*Department of Economi...,Sincerely,dvdmson @ gmail . Com,na,NB
3,Ê vendor payment,Are you around? I need to pay a vendor with th...,12/27/18\n,na,na,na,"gift card, meeting",Y,"University of California, Berkeley",na,ÊÊXXX.subdomain.berkeley.edu@gmail.com,na,NB
6,Message from human resources,Dear XXXXX@berkeley.edu(link sends e-mail)\n\n...,4/13/17,9:29:54 PM PDT,na,click here,HR,Y,Berkeley University Of California HR Departmen...,Thank you,HR@berkeley.edu,na,NB
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Sales Contract PO:#224906999,2 new message,"February 12th, 2019",9.32am,tue,review,"sales, review",Y,Y,thanks,Y,na,B
185,new bill from Ian,your bill is here,"February 12th, 2019",2.15pm,tue,invoice connect,"bill,",Y,Y,thank you,Y,na,B
186,Re: Payment Invoice,please check your,"February 12th, 2019",2.17am EST,na,na,"invoice, payment",Y,Y,Thank you,Y,na,B
187,KSU Infringement,"email has been reposted , regulation","February 9th, 2019",11.21am EST,na,URL Redacted,"reported, regulations, policies",Y,Y,Sincerely,Y,na,B
188,We recieved your request,request to deactivate,"January 29th, 2019",2.11pm,tue,cancel,"request, cancel, deactivate,",Y,Y,na,Y,offcie 365,B

In [23]:
df["text"]=df["Email_Subject"].fillna("")+ " " +df["Email_Content"].fillna("")
X=df["text"]
df["label"]=df["To"].apply(lambda x: 1 if x =="B" else 0)
y=df["label"]

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
vectorizer=TfidfVectorizer()
X_train_vec=vectorizer.fit_transform(X_train)
X_test_vec=vectorizer.transform(X_test)

model=LogisticRegression()
model.fit(X_train_vec,y_train)
predictions=model.predict(X_test_vec)
accuracyresult=accuracy_score(y_test,predictions)
print("Accuracy:", accuracyresult)

Accuracy: 0.9142857142857143

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.91      1.00      0.96        32

    accuracy                           0.91        35
   macro avg       0.46      0.50      0.48        35
weighted avg       0.84      0.91      0.87        35

c:\Users\User\Desktop\fashion-suggestion\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\User\Desktop\fashion-suggestion\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\User\Desktop\fashion-suggestion\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])